# Generated by Django 5.1.2 on 2024-11-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_cycles', models.IntegerField()),
                ('health_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='vehicle_data.vehicle')),
            ],
        ),
    ]
