# Generated by Django 5.1.2 on 2024-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('battery_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_range', models.CharField(max_length=100)),
            ],
        ),
    ]
